NetWealthCurrencyConvertWeb/Models/ConvertCurrencyRequestModel.cs
namespace NetWealthCurrencyConvertWeb.Models
{
    public class ConvertCurrencyRequestModel
    {
        public string CurrencyCode { get; set; }
        public decimal Amount { get; set; }
        public string DestinationCurrencyCode { get; set; }
    }
}

NetWealthCurrencyConvertWeb/Models/ConvertCurrencyResponseModel.cs
namespace NetWealthCurrencyConvertWeb.Models
{
    public class ConvertCurrencyResponseModel
    {
        public DateTime ConvertedDateTime { get; set; } 
        public string CurrencyCode { get; set; } = string.Empty;
        public decimal Amount { get; set; } 
        public string DestinationCurrencyCode { get; set; } = string.Empty;
        public decimal ConvertedAmount { get; set; }
        public DateTime LastUpdatedTS { get; set; }
        public string Status { get; set; }
        public string? Message { get; set; }
    }
}

NetWealthCurrencyConvertWeb/Models/ConvertCurrencyViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace NetWealthCurrencyConvertWeb.Models
{
    public class ConvertCurrencyViewModel
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "You must select a currency to convert from.")]
        public string CurrencyCode { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "You must enter an amount to convert")]
        public decimal Amount { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "You must select a currency to convert to.")]
        public string DestinationCurrencyCode { get; set; } 
        [JsonIgnore] 
        public List<CurrencyListModel> CurrencyList { get; set; } = new List<CurrencyListModel>();
        [JsonIgnore]
        public string? Message { get; set; }
        [JsonIgnore]
        public string? ConversionDisplayHeader { get; set; }
        [JsonIgnore]
        public string? ConversionDisplayMessage { get; set; }
        [JsonIgnore]
        public string? lastUpdatedDisplayMessage { get; set; }
    }
}

NetWealthCurrencyConvertWeb/Models/CurrencyListModel.cs
namespace NetWealthCurrencyConvertWeb.Models
{
    public class CurrencyListModel
    { 
        public string CurrencyCode { get; set; } = string.Empty;
        public string Currency { get; set; } = string.Empty; 
        public string DisplayText
        {
            get { return $"{CurrencyCode} - {Currency}"; }
        }
    } 
}

NetWealthCurrencyConvertWeb/Models/ErrorViewModel.cs
namespace NetWealthCurrencyConvertWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NetWealthCurrencyConvertWeb/Controllers/CurrencyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NetWealthCurrencyConvertWeb.Models;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Globalization;
using System.Text;

namespace NetWealthCurrencyConvertWeb.Controllers
{
    public class CurrencyController : Controller
    {
        private readonly ILogger<CurrencyController> _logger;

        public CurrencyController(ILogger<CurrencyController> logger)
        {
            _logger = logger;
        } 
         
        public async Task<IActionResult> CurrencyConverter()
        {
            Models.ConvertCurrencyViewModel viewModel = new Models.ConvertCurrencyViewModel();
             
            viewModel.CurrencyList = await Api.CurrencyAPI.GetCurrencyList(); 
            viewModel.Amount = 0; 

            return View(viewModel);
        }

        [HttpPost] 
        public async Task<IActionResult> CurrencyConverter(Models.ConvertCurrencyViewModel viewModel)
        {
            if(viewModel == null)
            {
                return View("Error");
            }

            viewModel.CurrencyList = await Api.CurrencyAPI.GetCurrencyList();

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            Models.ConvertCurrencyResponseModel oResponse = await Api.CurrencyAPI.ConvertCurrency(viewModel);
            if (oResponse != null)
            {
                if (oResponse.Status == "OK")
                {
                    viewModel.ConversionDisplayHeader = $"{TruncateDecimal(oResponse.ConvertedAmount, 2).ToString()} {oResponse.DestinationCurrencyCode}";
                    viewModel.ConversionDisplayMessage = $"{oResponse.Amount} {oResponse.CurrencyCode} = {oResponse.ConvertedAmount} {oResponse.DestinationCurrencyCode}";
                    viewModel.lastUpdatedDisplayMessage = $"Last Updated : {oResponse.LastUpdatedTS}";
                }
                else
                {
                    viewModel.ConversionDisplayMessage = String.Empty;
                    viewModel.Message = oResponse.Message;
                }
            }
            return View(viewModel);
        }
        private decimal TruncateDecimal(decimal value, int precision)
        {
            decimal step = (decimal)Math.Pow(10, precision);
            decimal tmp = Math.Truncate(step * value);
            return tmp / step;
        }

        public IActionResult ViewAPIEndpoints()
        {
            return Redirect($"{Api.CurrencyAPI.ApiURL}swagger/index.html");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NetWealthCurrencyConvertWeb/Views/Currency/CurrencyConverter.cshtml
@model ConvertCurrencyViewModel 
@{
    ViewData["Title"] = "Currency Converter";
} 
<div class="text-center">
    <h1 class="display-4">Convert Currency</h1>
    <p>View API end points <a asp-controller="Currency" asp-action="ViewAPIEndpoints" target="_blank">here</a>.</p>
      
    <form method="post" enctype="multipart/form-data" asp-action="CurrencyConverter" asp-controller="Currency" > 
        <div class="row">
            <div class="column-amount">
                <div class="column-header">Amount</div>
                <div class="column-content column-content-input">
                    @Html.EditorFor(x => Model.Amount)  
                </div> 
            </div>
            <div class="column-dropdown">
                <div class="column-header">Convert From</div>
                <div class="column-content column-content-input">
                    @Html.DropDownListFor(x => x.CurrencyCode, new SelectList(Model.CurrencyList, "CurrencyCode", "DisplayText"), " - Select Currency - ")
                    @Html.ValidationMessageFor(x => x.CurrencyCode)
                </div>
            </div>
            <div class="column-dropdown">
                <div class="column-header">Convert To</div>
                <div class="column-content column-content-input">
                    @Html.DropDownListFor(x => x.DestinationCurrencyCode, new SelectList(Model.CurrencyList, "CurrencyCode", "DisplayText"), " - Select Currency - ") 
                    @Html.ValidationMessageFor(x => x.DestinationCurrencyCode)
                </div>
            </div> 
            <div class="column-button"> 
                <div class="column-header"></div> 
                <div class="column-content ">
                    <input type="submit" value="Calculate" class="btn btn-primary" />  
                </div>
            </div> 
            <div class="conversionresult-header">  
                @Html.DisplayFor(x => Model.ConversionDisplayHeader)  
            </div>
            <div class="conversionresult-content">  
                @Html.DisplayFor(x => Model.ConversionDisplayMessage)  
            </div>
            <div class="conversionresult-contentsmall">  
                @Html.DisplayFor(x => Model.lastUpdatedDisplayMessage)  
            </div> 
            <div class="conversionresult-error">  
                @Html.DisplayFor(x => Model.Message)  
            </div>
            
        </div> 
    </form>  
</div> 

NetWealthCurrencyConvertWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetWealthCurrencyConvertWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetWealthCurrencyConvertWeb.styles.css" asp-append-version="true" />
    <script language="JavaScript" type="text/javascript" src="~/js/jquery-3.6.0.js"></script> 
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Currency" asp-action="CurrencyConverter">NetWealth Currency Converter</a> 
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NetWealthCurrencyConvertWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>